test:
	java -cp C:\Users\TheNo\Downloads\processing-4.3.2-windows-x64\processing-4.3.2\core\library\core.jar Sketch.java
	java -cp C:\Users\TheNo\Downloads\processing-4.3.2-windows-x64\processing-4.3.2\core\library\core.jar:. Sketch